### ISSUE TITLE
Create contract for Pigify Presale

### ISSUE THREAD

**Issue by dresnite** [PigifyApp/pigify-core#4]
### Description
As part of the Pigify token presale, we need to create a BSC contract called `PigifyPresaleManager` to manage the sale of PGY tokens. The contract should have the following features:

- A method called "buyWithUSDT(amountUSDT)" to exchange USDT for PGY with the rate 1 PGY = 0.4 USDT.
- A method called "buyWithBUSD(amountBUSD)" to exchange BUSD for PGY with the rate 1 PGY = 0.4 BUSD.
- A method called "buyWithUSDC(amountUSDC)" to exchange USDC for PGY with the rate 1 PGY = 0.4 USDC.
- A method called "withdrawSales()" that can only be called by the contract creator. This method should send all of the USDT, BUSD and USDC tokens from the contract to the contract creator.
- A method called "depositPGY()" that only the contract creator should be able to call. This method will deposit PGY for the other "buy" methods to work.

The purpose of this contract is to facilitate the presale of Pigify tokens and ensure that it is done securely and efficiently. The contract should be thoroughly tested to ensure that it is functioning properly before deploying it to the BSC mainnet.

### Tasks
- [x] Write the PigifyPresaleManager contract code.
- [ ] Test the contract code thoroughly.
- [ ] Deploy the contract to the BSC mainnet.
- [ ] Publicly verify the contract code on BSCScan.
- [ ] Provide clear instructions on how to participate in the presale using the contract.

**Comment by dresnite** [comment]
Added the contract code to https://github.com/pigifyapp/pigify-core/commit/a1450e69d3ba5615a75e794b0263c409268c1364. It still needs to pass our private reviews and tests before it is deployed to the mainnet.
